FROM nvidia/cuda:10.0-base as base

RUN apt-get -y update \
    && apt-get install -y software-properties-common \
    && apt-get -y update \
    && add-apt-repository universe

RUN apt-get -y install python3.8 \
    && apt-get -y install python3-pip

# note: flag -y is same as --assume-yes which means it will answer yes in any prompts


RUN mkdir /work/
WORKDIR /work/

RUN pip3 install virtualenv \
    && virtualenv -p python3.8 venv

RUN . venv/bin/activate

COPY ./src/requirements.txt /work/requirements.txt
RUN pip3 install -r requirements.txt

COPY ./src/ /work/

######## START NEW IMAGE: DEBUGGER ########
FROM base as debug
RUN pip3 install ptvsd

WORKDIR /work/
CMD python -m ptvsd --host 0.0.0.0 --port 5678 --wait usetf.py

######## START NEW IMAGE: PRODUCTION ########
FROM base as prod
CMD python usetf.py



# notes:
# to expose a port:
# EXPOSE 5000
# in case of memory limits try:
# sudo vim /etc/default/grub # edit GRUB_CMDLINE_LINUX as follows
# grep GRUB_CMDLINE_LINUX /etc/default/grub
# GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
# sudo update-grub
# sudo shutdown -r now